---

language: python
python:
  - 3.5
sudo: false
addons:
  apt:
    packages:
      - make
before_install:
  - cp files/home/homeassistant/.homeassistant/secrets.yaml.dist files/home/homeassistant/.homeassistant/secrets.yaml
install:
  - pip3 install homeassistant
before_script:
  - mkdir -p "$HOME/bin"
  - curl -Lso "$HOME/bin/shellcheck" https://github.com/caarlos0/shellcheck-docker/releases/download/v0.4.6/shellcheck
  - chmod +x "$HOME/bin/shellcheck"
  - export PATH="$HOME/bin:$PATH"
script:
  - make test
  - hass -c files/home/homeassistant/.homeassistant/ --script check_config
