---

language: python
python:
  - 3.5
sudo: required
services:
  - docker
addons:
  apt:
    packages:
      - make
cache: pip
before_install:
  - cp homeassistant/secrets.yaml.dist homeassistant/secrets.yaml
install:
  - make install
before_script:
  - mkdir -p "$HOME/bin"
  - curl -Lso "$HOME/bin/shellcheck" https://github.com/caarlos0/shellcheck-docker/releases/download/v0.4.6/shellcheck
  - chmod +x "$HOME/bin/shellcheck"
  - export PATH="$HOME/bin:$PATH"
script:
  - make test
