---

language: c
sudo: false
addons:
  apt:
    packages:
      - make
before_script:
  - mkdir -p "$HOME/bin"
  - curl -Lso "$HOME/bin/shellcheck" https://github.com/caarlos0/shellcheck-docker/releases/download/v0.4.6/shellcheck
  - chmod +x "$HOME/bin/shellcheck"
  - export PATH="$HOME/bin:$PATH"
script:
  - make test
