---

version: '3'

services:
  home-assistant:
    build: .
    image: bdossantos/home-assistant
    container_name: home-assistant
    volumes:
      - /dev/bus/usb:/dev/bus/usb
      - /volume1/homes/admin/Code/bds.home/homeassistant:/config
    environment:
      - TZ=Europe/Paris
    ports:
      - 0.0.0.0:8080:8080/tcp
    network_mode: host
    privileged: true
    restart: always
  homeassistant-postgresql:
    image: postgres:10
    container_name: homeassistant-postgresql
    volumes:
      - /volume1/docker/homeassistant-postgres/data:/var/lib/postgresql/data
    env_file:
      - /volume1/docker/homeassistant-postgres/.env
    command: -p 5433
    ports:
      - 127.0.0.1:5433:5433/tcp
    network_mode: host
    restart: always
