---

version: '3'

services:
  netdata:
    image: netdata/netdata:v1.11.1
    container_name: netdata
    cap_add:
      - SYS_PTRACE
    security_opt:
      - apparmor:unconfined
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /volume1/docker/netdata/config:/etc/netdata:rw
      - /volume1/docker/netdata/log:/var/log/netdata:rw
      - /volume1/homes/admin/Code/bds.home/scripts/netdata:/netdata
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
    env_file:
      - /volume1/homes/admin/Code/bds.home/.env
    ports:
      - 192.168.1.250:19999:19999/tcp
    network_mode: host
    restart: always
  home-assistant:
    build: .
    image: bdossantos/home-assistant
    container_name: home-assistant
    devices:
      - /dev/ttyACM0:/dev/ttyACM0
    volumes:
      - /dev/bus/usb:/dev/bus/usb:ro
      - /volume1/homes/admin/Code/bds.home/homeassistant:/config
    environment:
      - TZ=Europe/Paris
    ports:
      - 192.168.1.250:8080:8080/tcp
    network_mode: host
    privileged: true
    restart: always
  homeassistant-postgresql:
    image: postgres:11.1
    container_name: homeassistant-postgresql
    volumes:
      - /volume1/docker/homeassistant-postgres/data:/var/lib/postgresql/data
    env_file:
      - /volume1/homes/admin/Code/bds.home/.env
    command: -p 5433
    ports:
      - 127.0.0.1:5433:5433/tcp
    network_mode: host
    restart: always
