---
- platform: bayesian
  name: "in_bed"
  prior: 0.5
  probability_threshold: 0.85
  observations:
    - entity_id: "group.family"
      prob_given_true: 0.9
      prob_given_false: 0.5
      platform: "state"
      to_state: "home"
    - entity_id: "binary_sensor.livingroom_motion_sensor"
      prob_given_true: 0.4
      prob_given_false: 0.2
      platform: "state"
      to_state: "off"
    - entity_id: "binary_sensor.hallway_motion_sensor"
      prob_given_true: 0.5
      prob_given_false: 0.4
      platform: "state"
      to_state: "off"
    - entity_id: "binary_sensor.bedroom_motion_sensor"
      prob_given_true: 0.5
      platform: "state"
      to_state: "on"
    - entity_id: "binary_sensor.kitchen_motion_sensor"
      prob_given_true: 0.4
      prob_given_false: 0.2
      platform: "state"
      to_state: "off"
    - entity_id: "sun.sun"
      prob_given_true: 0.7
      platform: "state"
      to_state: "below_horizon"
    - entity_id: "group.all_lights"
      prob_given_true: 0.9
      prob_given_false: 0.4
      platform: "state"
      to_state: "off"
