---

homeassistant:
  auth_providers:
    - type: homeassistant
  latitude: !secret home_latitude
  longitude: !secret home_longitude
  elevation: 30
  unit_system: metric
  time_zone: Europe/Paris
  name: BDS Home
  customize: !include_dir_merge_named customize

logger:
  default: warning
  logs:
    homeassistant.components.http.ban: warning

system_health:

updater:
  reporting: false

frontend:

config:

http:
  server_port: 8080
  ip_ban_enabled: 'True'
  login_attempts_threshold: 3
  api_password: !secret api_password
  use_x_forwarded_for: true
  trusted_proxies:
    - 127.0.0.1
    - 192.168.1.254
    - ::1

discovery:

conversation:

history:

logbook:

map:

sun:

tts:
  - platform: google
    cache: true
    cache_dir: /tmp/tts
    time_memory: 300
    language: 'en'

recorder:
  db_url: !secret db_url
  purge_interval: 1
  purge_keep_days: 30

hue:
  bridges:
    - host: 192.168.1.249
      filename: phue.conf
      allow_unreachable: true
      allow_hue_groups: false

scene: !include_dir_list scene

light: !include_dir_merge_list light

person: !include_dir_merge_list person

sensor: !include_dir_merge_list sensor

binary_sensor: !include_dir_merge_list binary_sensor

device_tracker: !include_dir_merge_list device_tracker

sonos:
  media_player:
    hosts:
      - 192.168.1.248
      - 192.168.1.245

switch:
  - platform: tplink
    host: 192.168.1.240
  - platform: tplink
    host: 192.168.1.241
    name: Hot Water Cylinder

nest:
  client_id: !secret nest_client_id
  client_secret: !secret nest_client_secret

netatmo:
  api_key: !secret netatmo_api_key
  secret_key: !secret netatmo_secret_key
  username: !secret netatmo_username
  password: !secret netatmo_password
  discovery: 'True'

group:
  default_view:
    name: Home
    icon: mdi:home
    view: 'True'
    entities:
      - group.family
      - group.input_booleans
      - group.door
      - group.hall
      - group.toilet
      - group.kitchen
      - group.livingroom
      - group.bedroom
      - group.dressing
      - group.bathroom
      - group.scenes
  sensor_view:
    name: Sensors
    icon: mdi:thermometer
    view: 'True'
    entities:
      - group.door
      - group.netatmo
      - group.darksky
      - group.air_quality
      - history_graph.indoor_temperature
      - history_graph.indoor_luminance
      - history_graph.indoor_co2
      - history_graph.indoor_humidity
      - history_graph.indoor_noise
      - history_graph.outdoor_temperature
      - history_graph.outdoor_humidity
      - history_graph.outdoor_ozone
      - group.apc_be700g
  system_view:
    name: System
    icon: mdi:toolbox
    view: 'True'
    entities:
      - group.all_automations
      - group.all_scripts
  door:
    name: Door
    entities:
      - binary_sensor.front_door
      - binary_sensor.livingroom_door
  bathroom:
    name: Bathroom
    entities:
      - light.bathroom1
  bedroom:
    name: Bedroom
    entities:
      - light.bedroom1
      - light.bedroom2
      - light.bedroom3
      - binary_sensor.bedroom_motion_sensor
      - sensor.bedroom_motion_luminance
      - sensor.bedroom_motion_temperature
      - media_player.bedroom
  hall:
    name: Hall
    entities:
      - light.hall1
      - binary_sensor.hallway_nest_protect_online
      - sensor.hallway_nest_protect_battery_health
      - sensor.hallway_nest_protect_co_status
      - sensor.hallway_nest_protect_color_status
      - sensor.hallway_nest_protect_smoke_status
      - binary_sensor.hallway_motion_sensor
      - sensor.hallway_motion_luminance
      - sensor.hallway_motion_temperature
  toilet:
    name: Toilet
    entities:
      - switch.hot_water_cylinder
      - sensor.hot_water_cylinder_amps
      - sensor.hot_water_cylinder_volts
      - sensor.hot_water_cylinder_watts
      - sensor.hot_water_cylinder_today_kwh
      - sensor.hot_water_cylinder_total_kwh
  kitchen:
    name: Kitchen
    entities:
      - light.kitchen1
      - switch.smartplug_kitchen1
      - binary_sensor.kitchen_motion_sensor
      - sensor.kitchen_motion_luminance
      - sensor.kitchen_motion_temperature
      - binary_sensor.fridge_motion_sensor
      - sensor.fridge_motion_luminance
      - sensor.fridge_motion_temperature
  livingroom:
    name: Living Room
    entities:
      - light.livingroom1
      - light.livingroom2
      - light.livingroom3
      - light.livingroom4
      - binary_sensor.livingroom_motion_sensor
      - sensor.livingroom_motion_luminance
      - sensor.livingroom_motion_temperature
      - media_player.living_room
      - sensor.netatmo_indoor_temperature
      - sensor.netatmo_indoor_co2
      - sensor.netatmo_indoor_humidity
      - sensor.netatmo_indoor_noise
      - sensor.apc_be700g_input_voltage
      - sensor.apc_be700g_load
  dressing:
    name: Dressing
    entities:
      - light.dressing1
      - binary_sensor.dressing1_motion_sensor
      - sensor.dressing1_motion_luminance
      - sensor.dressing1_motion_temperature
      - light.dressing2
      - binary_sensor.dressing2_motion_sensor
      - sensor.dressing2_motion_luminance
      - sensor.dressing2_motion_temperature

  scenes:
    name: Scenes
    entities:
      - scene.all_lights_off
      - scene.nightlight
      - scene.candle
      - scene.candle_bedroom
      - scene.relax
      - scene.concentrate
      - scene.reading
      - scene.energize
      - scene.arctic
  air_quality:
    name: Paris Air quality
    entities:
      - sensor.us_air_pollution_level
      - sensor.us_air_quality_index
      - sensor.us_main_pollutant
  netatmo:
    name: Indoor metrics
    entities:
      - sensor.netatmo_indoor_co2
      - sensor.netatmo_indoor_humidity
      - sensor.netatmo_indoor_noise
      - sensor.netatmo_indoor_pressure
      - sensor.netatmo_indoor_temperature
  darksky:
    name: Outdoor metrics
    entities:
      - sensor.dark_sky_daily_summary
      - sensor.dark_sky_humidity
      - sensor.dark_sky_ozone
      - sensor.dark_sky_precip_intensity
      - sensor.dark_sky_precip_probability
      - sensor.dark_sky_temperature
      - sensor.dark_sky_uv_index
      - sensor.dark_sky_wind_speed
  apc_be700g:
    name: APC BE700G
    entities:
      - sensor.apc_be700g_status
      - sensor.apc_be700g_battery_charge
      - sensor.apc_be700g_battery_runtime
      - sensor.apc_be700g_battery_voltage
      - sensor.apc_be700g_beeper_status
      - sensor.apc_be700g_input_voltage
      - sensor.apc_be700g_load
  tile:
    name: Tile
    entities:
      - device_tracker.tile_home_keys
      - device_tracker.tile_home_keys_double
      - device_tracker.tile_passport
  input_booleans:
    name: Home modes
    entities:
      - input_boolean.vacation_mode
      - input_boolean.guest_mode
  family:
    name: Family
    entities:
      - person.benjamin
      - person.laura
  all_media_players:
    name: All media players
    entities:
      - media_player.living_room
      - media_player.bedroom
  all_switchs:
    name: All switchs
    entities:
      - switch.smartplug_kitchen1

input_select:
  benjamin_status_dropdown:
    name: Benjamin
    options:
      - Home
      - Just Arrived
      - Just Left
      - Away
      - Extended Away
    initial: Home

history_graph: !include_dir_merge_list history_graph

automation: !include_dir_merge_list automation

android_ip_webcam:
  - host: 192.168.1.20
    port: 8080
    username: !secret android_ip_webcam_username
    password: !secret android_ip_webcam_password
    scan_interval: 10
    sensors:
      - audio_connections
      - battery_level
      - battery_temp
      - battery_voltage
      - light
      - motion
      - pressure
      - proximity
      - sound
      - video_connections
    switches:
      - exposure_lock
      - ffc
      - focus
      - gps_active
      - night_vision
      - overlay
      - torch
      - whitebalance_lock
      - video_recording

script:
  sonos_say:
    alias: 'Sonos TTS script'
    sequence:
      - service: media_player.sonos_snapshot
        data_template:
          entity_id: "{{ sonos_entity }}"
      - service: media_player.sonos_unjoin
        data_template:
          entity_id: "{{ sonos_entity }}"
      - service: media_player.volume_set
        data_template:
          entity_id: "{{ sonos_entity }}"
          volume_level: "{{ volume }}"
      - service: tts.google_say
        data_template:
          entity_id: "{{ sonos_entity }}"
          message: "{{ message }}"
      - delay: "{{ delay or '00:00:05' }}"
      - service: media_player.sonos_restore
        data_template:
          entity_id: "{{ sonos_entity }}"

input_boolean: !include input_boolean.yaml

notify:
  - name: slack
    platform: slack
    api_key: !secret slack_api_key
    default_channel: '#general'

zone:
  - name: Work
    latitude: !secret work_latitude
    longitude: !secret work_longitude
    elevation: 40
    icon: mdi:worker
    radius: 100

proximity:
  home:
    zone: home
    devices:
      - device_tracker.tile_bag_tnf_basecamp_s_black
      - device_tracker.tile_bag_tnf_borealis_backpack
      - device_tracker.tile_home_keys
      - device_tracker.tile_home_keys_double
      - device_tracker.tile_passport
    tolerance: 50
  work:
    zone: work
    devices:
      - device_tracker.tile_bag_pro_laptop_briefcase
      - device_tracker.tile_home_keys
    tolerance: 100

zwave:
  usb_path: /dev/ttyACM0
  network_key: !secret z_wave_network_key
