---
- alias: "Fridge temperature"
  trigger:
    platform: numeric_state
    entity_id: sensor.fridge_motion_temperature
    above: 0
    below: 6
  action:
    service: notify.slack
    data_template:
      message: ""
      data:
        attachments:
          - color: >
              warning
            title: >
              :warning: Warning
            text: |
              Fridge temperature is {{ states('sensor.fridge_motion_temperature') }} :thermometer:
