---

- alias: 'Weekdays morning routine'
  initial_state: 'True'
  trigger:
    - platform: time
      at: '07:15:00'
  condition:
    - condition: state
      entity_id: group.family
      state: 'home'
    - condition: time
      weekday:
        - mon
        - tue
        - wed
        - thu
        - fri
    - condition: state
      entity_id: input_boolean.guest_mode
      state: 'off'
  action:
    - service: script.morning
