---

- alias: 'Weekdays morning routine'
  initial_state: 'True'
  trigger:
    - platform: time
      at: '07:15:00'
  condition:
    - condition: state
      entity_id: group.family
      state: 'home'
    - condition: time
      weekday:
        - mon
        - tue
        - wed
        - thu
        - fri
    - condition: state
      entity_id: input_boolean.guest_mode
      state: 'off'
  action:
    - service: light.turn_on
      entity_id: light.bedroom_lights
      data:
        transition: 1200
        brightness_pct: 30
        xy_color: [0.561, 0.404]
