---
- alias: "Nest Protect smoke or carbon monoxide emergency"
  initial_state: "True"
  trigger:
    platform: state
    entity_id:
      - sensor.hallway_nest_protect_smoke_status
      - sensor.hallway_nest_protect_co_status
    to: "Emergency"
  action:
    - service: light.turn_on
      entity_id:
        - group.all_lights
      data:
        flash: long
        brightness_pct: 100
        white_value: 255
        kelvin: 4100
    - service: light.turn_on
      entity_id:
        - group.all_lights
    - service: notify.slack
      data_template:
        message: ""
        data:
          attachments:
            - color: >
                danger
              title: >
                :sos: Fatal
              text: |
                There's smoke or carbon monoxide detected! :skull:
    - service: script.sonos_say
      data:
        sonos_entity: group.all_media_players
        volume: 0.5
        message: |
          There's smoke or carbon monoxide detected!

- alias: "Nest Protect is Offline"
  initial_state: "True"
  trigger:
    platform: state
    entity_id:
      - binary_sensor.hallway_nest_protect_online
    from: "on"
  action:
    - service: notify.slack
      data_template:
        message: ""
        data:
          attachments:
            - color: >
                warning
              title: >
                :warning: Warning
              text: |
                Nest protect is Offline!
    - service: script.sonos_say
      data:
        sonos_entity: group.all_media_players
        volume: 0.5
        message: |
          'Nest protect is Offline!'

- alias: "Nest Protect is back Online"
  initial_state: "True"
  trigger:
    platform: state
    entity_id:
      - binary_sensor.hallway_nest_protect_online
    to: "on"
  action:
    - service: notify.slack
      data_template:
        message: ""
        data:
          attachments:
            - color: >
                good
              title: >
                :information_source: Information
              text: |
                Nest protect is back Online!
    - service: script.sonos_say
      data:
        sonos_entity: group.all_media_players
        volume: 0.5
        message: |
          Nest protect is back Online!
