---
- alias: "UPS status changed"
  initial_state: "True"
  trigger:
    platform: state
    entity_id:
      - sensor.ups_status
  action:
    - service: notify.slack
      data_template:
        message: ""
        data:
          attachments:
            - color: >
                danger
              title: >
                :sos: Fatal
              text: |
                APC status summary :battery:

                Status: {{ states("sensor.ups_status") }}
                Battery: {{ states("sensor.ups_battery_charge") }}
                Battery runtime: {{ states("sensor.ups_battery_runtime") }}
                Battery voltage: {{ states("sensor.ups_battery_voltage") }}
                Input voltage: {{ states("sensor.ups_input_voltage") }}
                Load: {{ states("sensor.ups_load") }}

- alias: "Power outage finished"
  initial_state: "True"
  trigger:
    platform: state
    entity_id:
      - sensor.ups_status_data
    from: "OB DISCHRG"
    to: "OL CHRG"
  action:
    - service: notify.slack
      data_template:
        message: ""
        data:
          attachments:
            - color: >
                good
              title: >
                :information_source: Information
              text: |
                Power is back! :battery:

    # wait few minutes to let hue bridge reboot after a power outage
    # TODO: buy an APC with more battery backed slots
    - delay: "00:02:00"
    - service: notify.slack
      data_template:
        message: ""
        data:
          attachments:
            - color: >
                good
              title: >
                :information_source: Information
              text: |
                Turn all lights are off after the power outage :bulb:
    - service: light.turn_off
      entity_id: all
