---

- alias: 'APC status changed'
  initial_state: 'True'
  trigger:
    platform: state
    entity_id:
      - sensor.apc_be700g_status
  action:
    - service: notify.slack
      data_template:
        message: ''
        data:
          attachments:
            - color: >
                danger
              title: >
                :sos: Fatal
              text: |
                APC status summary :battery:

                Status: {{ states("sensor.apc_be700g_status") }}
                Battery: {{ states("sensor.apc_be700g_battery_charge") }}
                Battery runtime: {{ states("sensor.apc_be700g_battery_runtime") }}
                Battery voltage: {{ states("sensor.apc_be700g_battery_voltage") }}
                Input voltage: {{ states("sensor.apc_be700g_input_voltage") }}
                Load: {{ states("sensor.apc_be700g_load") }}

- alias: 'Power outage finished'
  initial_state: 'True'
  trigger:
    platform: state
    entity_id:
      - sensor.apc_be700g_status_data
    from: 'OB DISCHRG'
    to: 'OL CHRG'
  action:
    - service: notify.slack
      data_template:
        message: ''
        data:
          attachments:
            - color: >
                good
              title: >
                :information_source: Information
              text: |
                Power is back! :battery:

    # wait few minutes to let hue bridge reboot after a power outage
    # TODO: buy an APC with more battery backed slots
    - delay: '00:02:00'
    - service: notify.slack
      data_template:
        message: ''
        data:
          attachments:
            - color: >
                good
              title: >
                :information_source: Information
              text: |
                Turn all lights are off after the power outage :bulb:
    - service: scene.turn_on
      entity_id: scene.all_lights_off
