---
- alias: "Intrusion detection"
  initial_state: "True"
  trigger:
    platform: state
    entity_id:
      - binary_sensor.bedroom_motion_sensor
      - binary_sensor.front_door
      - binary_sensor.hallway_motion_sensor
      - binary_sensor.kitchen_motion_sensor
      - binary_sensor.livingroom_motion_sensor
    to: "on"
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: group.family
        state: "not_home"
      - condition: state
        entity_id: input_boolean.guest_mode
        state: "off"
  action:
    - service: notify.slack
      data_template:
        message: ""
        data:
          attachments:
            - color: >
                danger
              title: >
                :sos: Fatal
              text: |
                Intrusion detected!
