---

- platform: statistics
  entity_id: sensor.bedroom_motion_temperature
  name: bedroom_temperature

- platform: statistics
  entity_id: sensor.hallway_motion_temperature
  name: hallway_temperature

- platform: statistics
  entity_id: sensor.kitchen_motion_temperature
  name: kitchen_temperature

- platform: statistics
  entity_id: sensor.livingroom_motion_temperature
  name: livingroom_temperature

- platform: statistics
  entity_id: sensor.bedroom_motion_luminance
  name: bedroom_luminance

- platform: statistics
  entity_id: sensor.bedroom_motion_luminance
  name: bedroom_luminance

- platform: statistics
  entity_id: sensor.kitchen_motion_luminance
  name: kitchen_luminance

- platform: statistics
  entity_id: sensor.livingroom_motion_luminance
  name: livingroom_luminance

- platform: history_stats
  name: Time in bed
  entity_id: binary_sensor.in_bed
  state: 'on'
  type: time
  end: '{{ now() }}'
  duration:
    hours: 24
