---
- platform: google_wifi
  host: 192.168.1.253
  monitored_conditions:
    - current_version
    - new_version
    - uptime
    - last_restart
    - status

- platform: nut
  name: APC BE700G
  host: 192.168.1.250
  username: ups
  port: 3493
  resources:
    - battery.charge
    - battery.charge.low
    - battery.charge.warning
    - battery.date
    - battery.mfr.date
    - battery.runtime
    - battery.voltage
    - battery.voltage.nominal
    - input.voltage
    - input.voltage.nominal
    - ups.beeper.status
    - ups.load
    - ups.status
    - ups.status.display
    - ups.timer.reboot
    - ups.timer.shutdown

- platform: systemmonitor
  resources:
    - type: disk_use_percent
      arg: /
    - type: memory_use
    - type: memory_free
    - type: processor_use
    - type: network_in
      arg: eth0
    - type: network_out
      arg: eth0
    - type: last_boot
