---

homeassistant:
  latitude: !secret home_latitude
  longitude: !secret home_longitude
  elevation: 30
  unit_system: metric
  time_zone: Europe/Paris
  name: BDS Home
  customize: !include_dir_merge_named customize

frontend:

config:

http:
  server_port: 8080
  ip_ban_enabled: 'True'
  login_attempts_threshold: 3

discovery:

conversation:

history:

logbook:

map:

sun:

tts:
  platform: google

recorder:
  db_url: postgres://@/homeassistant
  purge_interval: 1
  purge_keep_days: 365

light:
  platform: hue
  host: hue.bds.home
  filename: phue.conf
  allow_unreachable: true
  allow_in_emulated_hue: true
  allow_hue_groups: false

sensor:
  - platform: google_wifi
    host: 192.168.1.253
    monitored_conditions:
      - current_version
      - new_version
      - uptime
      - last_restart
      - status
  - platform: bbox
    monitored_variables:
      - down_max_bandwidth
      - up_max_bandwidth
      - current_down_bandwidth
      - current_up_bandwidth
  - platform: systemmonitor
    resources:
      - type: disk_use_percent
        arg: /
      - type: memory_use
      - type: memory_free
      - type: processor_use
      - type: network_in
        arg: eth0
      - type: network_out
        arg: eth0
      - type: last_boot
  - platform: speedtest
    minute:
      - 0
      - 30
    monitored_conditions:
      - ping
      - download
      - upload
  - platform: command_line
    name: CPU Temperature
    command: 'cat /sys/class/thermal/thermal_zone0/temp'
    unit_of_measurement: '°C'
    value_template: '{{ value | multiply(0.001) | round(2) }}'
  - platform: airvisual
    api_key: !secret airvisual_api_key
    monitored_conditions:
      - us
      - cn
    city: paris
    state: ile-de-france
    country: france
    radius: 10000
    show_on_map: false
  - platform: nest
  - platform: netatmo

binary_sensor:
  - platform: nest

device_tracker:
  - platform: nmap_tracker
    home_interval: 10
    hosts: 192.168.1.0/24
    interval_seconds: 10
    exclude:
      - 192.168.1.247
      - 192.168.1.248
      - 192.168.1.249
      - 192.168.1.250
      - 192.168.1.251
      - 192.168.1.252
      - 192.168.1.253
      - 192.168.1.254
    scan_options: '-F --host-timeout 5s'
  - platform: bluetooth_tracker
  - platform: bbox

media_player:
  - platform: sonos

nest:
  client_id: !secret nest_client_id
  client_secret: !secret nest_client_secret

netatmo:
  api_key: !secret netatmo_api_key
  secret_key: !secret netatmo_secret_key
  username: !secret netatmo_username
  password: !secret netatmo_password

group:
  default_view:
    name: Home
    icon: mdi:home
    view: yes
    entities:
      - group.bathroom
      - group.bedroom
      - group.hall
      - group.kitchen
      - group.livingroom
      - group.lights
      - group.people
      - group.all_automations
      - group.all_scripts
      - group.all_switches
  sensor_view:
    name: Sensors
    icon: mdi:thermometer
    view: yes
    entities:
      - group.speedtest
      - group.nestor
      - group.router
      - group.netatmo
      - group.air_quality
      - history_graph.indoor_temperature
      - history_graph.indoor_co2
      - history_graph.indoor_humidity
  bathroom:
    name: Bathroom
    entities:
      - light.bathroom1
  bedroom:
    name: Bedroom
    entities:
      - light.bedroom1
  hall:
    name: Hall
    entities:
      - light.hall1
      - sensor.hallway_nest_protect_battery_health
      - sensor.hallway_nest_protect_co_status
      - sensor.hallway_nest_protect_smoke_status
  kitchen:
    name: Kitchen
    entities:
      - light.kitchen1
  livingroom:
    name: Living Room
    entities:
      - light.livingroom1
      - media_player.living_room
      - group.router
      - group.nestor
      - sensor.netatmo_indoor_temperature
      - sensor.netatmo_indoor_co2
      - sensor.netatmo_indoor_humidity
  lights:
    name: Lights
    entities:
      - script.all_lights_off
      - script.all_lights_on
  router:
    name: Router
    entities:
      - sensor.bbox_currently_used_download_bandwidth
      - sensor.bbox_currently_used_upload_bandwidth
      - sensor.bbox_maximum_download_bandwidth
      - sensor.bbox_maximum_upload_bandwidth
      - history_graph.router_graph
  speedtest:
    name: Internet
    entities:
      - sensor.speedtest_ping
      - sensor.speedtest_download
      - sensor.speedtest_upload
  nestor:
    name: Nestor
    entities:
      - sensor.cpu_used
      - sensor.ram_used
      - sensor.cpu_temperature
      - history_graph.cpu_temperature
  air_quality:
    name: Paris Air quality
    entities:
      - sensor.us_air_pollution_level
      - sensor.us_air_quality_index
      - sensor.us_main_pollutant
  netatmo:
    name: Netatmo
    entities:
      - sensor.netatmo_indoor_co2
      - sensor.netatmo_indoor_humidity
      - sensor.netatmo_indoor_noise
      - sensor.netatmo_indoor_pressure
      - sensor.netatmo_indoor_temperature
      - sensor.netatmo_indoor_wifi
      - sensor.netatmo_outdoor_battery
      - sensor.netatmo_outdoor_humidity
      - sensor.netatmo_outdoor_radio
      - sensor.netatmo_outdoor_temperature
  people:
    name: People
    entities:
      - device_tracker.nexus_5x

history_graph:
  router:
    name: Router Graph
    entities:
      - sensor.bbox_currently_used_download_bandwidth
      - sensor.bbox_currently_used_upload_bandwidth
    hours_to_show: 12
    refresh: 30
  cpu_temperature:
    name: Nestor CPU temperature
    entities:
      - sensor.cpu_temperature
    hours_to_show: 12
    refresh: 30
  indoor_temperature:
    name: Indoor temperature
    entities:
      - sensor.netatmo_indoor_temperature
    hours_to_show: 168
    refresh: 600
  indoor_co2:
    name: Indoor CO2
    entities:
      - sensor.netatmo_indoor_co2
    hours_to_show: 168
    refresh: 600
  indoor_humidity:
    name: Indoor Humidity
    entities:
      - sensor.netatmo_indoor_humidity
    hours_to_show: 168
    refresh: 600

automation:
  - alias: 'Natural wake up light'
    trigger:
      platform: time
      at: '07:30:00'
    action:
      service: light.turn_on
      entity_id: light.bedroom1
      data:
        transition: 900
  - alias: 'Turn off music when I leave home'
    trigger:
      platform: state
      entity_id: device_tracker.nexus_5x
      from: 'home'
      to: 'not_home'
    action:
      service: media_player.turn_off

device_sun_light_trigger:
  light_group: group.all_lights
  light_profile: relax
  device_group: group.people
  disable_turn_off: 0

script:
  all_lights_off:
    sequence:
      - service: light.turn_off
        data:
          entity_id: group.all_lights
          transition: 15
  all_lights_on:
    sequence:
      - service: light.turn_on
        data:
          entity_id: group.all_lights
          brightness: 255
          color_temp: 260
          transition: 15

zone:
  - name: Work
    latitude: !secret work_latitude
    longitude: !secret work_longitude
    elevation: 40
    icon: mdi:worker
    radius: 100
